# NUMPY TUTORIAL 

In [1]:
import numpy as np  # Importing numpy as np

In [2]:
myarr = np.array([2, 3 , 4, 68], np.int8)  # Creating a numpy array with dtype

In [3]:
myarr # Printing the array

array([ 2,  3,  4, 68], dtype=int8)

In [4]:
myarr[0]

np.int8(2)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr.shape

(4,)

In [7]:
arr = np.array({1,2,34,5})

In [8]:
arr

array({1, 2, 34, 5}, dtype=object)

In [9]:
zeros = np.zeros((3,3))

In [10]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
zeros.shape

(3, 3)

In [12]:
zeros.size

9

In [13]:
zeros.dtype

dtype('float64')

In [14]:
a_range = np.arange(99)

In [15]:
a_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [16]:
a_range.shape

(99,)

In [17]:
a_range.size

99

In [18]:
a_range.dtype

dtype('int64')

In [19]:
a_range = a_range.reshape(9,11)

In [20]:
a_range

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [21]:
a_range.shape

(9, 11)

In [22]:
a_range = a_range.ravel()
a_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [23]:
arr = np.linspace(1,10,6)

In [24]:
arr

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [25]:
emt = np.empty((3,2))

In [26]:
emt

array([[ 1. ,  2.8],
       [ 4.6,  6.4],
       [ 8.2, 10. ]])

In [27]:
emt.shape

(3, 2)

In [28]:
print(np.empty_like(arr))

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [29]:
ide = np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [31]:
x = [[1,2,3],[4,5,6], [7,1,0]]

In [77]:
ar = np.array(x)

In [78]:
ar.sum(axis=0)

array([12,  8,  9])

In [34]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [36]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [37]:
ar.size

9

In [38]:
ar.nbytes

72

In [39]:
ar.ndim

2

In [40]:
one = np.array([1, 2, 4, 23, 3])

In [41]:
one.argmax()

np.int64(3)

In [42]:
one.argmin()

np.int64(0)

In [43]:
one.argsort()

array([0, 1, 4, 2, 3])

In [44]:
ar.argmax()

np.int64(6)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.argmax(axis=0)

array([2, 1, 1])

In [47]:
ar.argmin(axis=1)

array([0, 0, 2])

In [48]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [49]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [50]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [51]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [52]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [76]:
ar

array([[1, 2, 3],
       [4, 0, 6],
       [7, 1, 0]])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar2 = np.array([[1, 2, 1],
       [4,0, 6],
       [8, 2, 6]])

In [57]:
 ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  3,  6]])

In [58]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  2,  0]])

In [59]:
np.sqrt(ar * ar2)

array([[1.        , 2.        , 1.73205081],
       [4.        , 0.        , 6.        ],
       [7.48331477, 1.41421356, 0.        ]])

In [63]:
ar.sum()

np.int64(29)

In [64]:
ar.max()

np.int64(7)

In [65]:
ar.min()

np.int64(0)

In [81]:
np.where(ar >= 5)

(array([1, 1, 2]), array([1, 2, 0]))

In [79]:
np.count_nonzero(ar)

np.int64(8)

In [80]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [82]:
import sys

In [84]:
py_ar = [1, 2, 55, 0]

In [85]:
np_ar = np.array(py_ar)

In [87]:
sys.getsizeof(1) * len(py_ar)

112

In [90]:
np_ar.itemsize * np_ar.size

32

In [99]:
import numpy as np

arrr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arrr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [101]:
arrr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [96]:
arrr.shape

(2, 5)

In [102]:
arrr.dtype

dtype('int64')

In [103]:
string = np.array(["cherry", "banana", "apple"])

In [105]:
string.dtype

dtype('<U6')

In [106]:
f_num = np.array([1.1, 2.2, 3.4])

In [108]:
newarr = f_num.astype('i')

In [109]:
newarr

array([1, 2, 3], dtype=int32)

In [110]:
int_num = np.array([1, 0 ,3])

In [117]:
b_arr = int_num.astype(bool)

In [118]:
b_arr

array([ True, False,  True])